linters:
  "{src}/**/*.ts":
    - prettier --write --config ./.prettierrc.yml
    - tslint --project ./tsconfig.json -t codeFrame --fix
    - git add
  "**/package.json":
    - sort-package-json
    - git add
