language: node_js
node_js:
- 10

branches:
  only:
  - master
  - /^greenkeeper/.*$/

cache:
  directories:
  - $HOME/.npm
  - node_modules

#before_install:
#  - npm install npm@^6.0.0 -g

# npm ci will not work with branches created from greenkeeper, because those need to update the package-lock.json
# From https://github.com/greenkeeperio/greenkeeper-lockfile#npm:
# If dependencies in the package lock do not match those in package.json, npm ci will exit with an error, instead
# of updating the package lock.
install:
#  decide if running on greenkeeper branch or not
- case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;

notifications:
  email: false

before_script: npx greenkeeper-lockfile-update

script:
- npm run lint
- npm run test:prod
- npm run build

after_script: npx greenkeeper-lockfile-upload

after_success:
- npm run report-coverage
- npm run deploy-docs
- npx semantic-release
