language: node_js
node_js:
  - lts/*

cache: npm

install:
  - npm ci

notifications:
  email: false

script:
  - npm run lint:ci
  - npm run test:ci
  - npm run build
  - npm run docs:build

after_success:
  - npm run report-coverage
  - npm run docs:deploy
  - npx semantic-release
