language: node_js
node_js:
- lts/*

branches:
  only:
  - master
  - /^greenkeeper/.*$/

cache:
  directories:
  - node_modules

install:
- npm install

notifications:
  email: false

before_script: npx greenkeeper-lockfile-update

script:
- npm run lint
- npm run test:prod
- npm run build

after_script: npx greenkeeper-lockfile-upload

after_success:
- npm run report-coverage
- npm run deploy-docs
- npx semantic-release
