language: node_js
node_js:
- lts/*

branches:
  only:
  - master
  - /^greenkeeper/.*$/

cache:
  directories:
  - "$HOME/.npm"

before install:
- npm install npm@^6.0.0 -g

install:
- npm ci

notifications:
  email: false

script:
- npm run test:prod && npm run build

after_success:
- npm run report-coverage
- npm run deploy-docs
- npx semantic-release
